services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "student-academic-progress"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  server:
    depends_on:
      - db
    build:
      context: ./server
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/student-academic-progress?schema=public
      - PORT=80
    volumes:
      - ./server:/app

volumes:
  postgres_data:
